### ISSUE TITLE
make boot fails with QEMU >=3.0

### ISSUE THREAD

**Issue by gabriel-v** [linux-kernel-labs/linux#104]
The `vlan` parameter for `-net` [has been removed in QEMU 3.0](https://wiki.qemu.org/ChangeLog/3.0#Incompatible_changes).

After removing all `vlan=x,` entries in `tools/labs/qemu/Makefile` the vm doesn't boot.

**Comment by Sergiu121** [comment]
Fix can be found here [1]. Will merge soon.

[1] http://cursuri.cs.pub.ro/pipermail/so2/2019-March/007815.html

**Comment by razvand** [comment]
> Fix can be found here [1]. Will merge soon.
> 
> [1] http://cursuri.cs.pub.ro/pipermail/so2/2019-March/007815.html

@Sergiu121 , will you create a pull request for this?

**Comment by Sergiu121** [comment]
Solved in PR #127
