### ISSUE TITLE
hello_mod: loading out-of-tree module taints kernel

### ISSUE THREAD

**Issue by scttnlsn** [linux-kernel-labs/linux#136]
I'm following along with the "Kernel Modules" lab and whenever I try to load the `hello_mod.ko` module I get the following error:

```
hello_mod: loading out-of-tree module taints kernel
```

The output of `lsmod` is:

```
    Tainted: G  
hello_mod 16384 0 - Live 0xc884b000 (O)
```

And it looks like `Hello!` and `Goodbye!` are never actually printed to the syslog.
Any suggestions?

**Comment by dbaluta** [comment]
@scttnlsn The message you get it is not an error. It is just the kernel letting you know that you are loading
an 'out of tree module'. 

This message is harmless for the purpose of this exercise. 

For the 'Hello' and 'Goodbye' messages you the actual task is to figure out how to make the message appear. 

Did you run ``dmesg`` command and there was no message? Please read more about printk log levels.

**Comment by scttnlsn** [comment]
Got it- thanks.  I was expecting `pr_debug` to work like `pr_info` but I see that it is handled differently: https://linux-kernel-labs.github.io/master/labs/kernel_modules.html#dynamic-debugging  Thanks for your help!
