### ISSUE TITLE
How to creat boot images for powerpc (or other architecturs)?

### ISSUE THREAD

**Issue by petmos** [linux-kernel-labs/linux#137]
Is there a documentation available for other architecures than x86?

I tried to create a boot image for powerpc but it failed.
After "make boot ARCH=powerpc" I got:
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
gcc: error: unrecognized command line option ‘-mmultiple’; did you mean ‘-imultilib’?

**Comment by dbaluta** [comment]
Hi @petmos never tried for powerpc. Our current build system only supports arm and x86.

 but I think a good start is to look into:

```tools/labs/qemu/Makefile``` and ```tools/labs/qemu/qemu.sh```

Then fix the $ARCH variable, I thin it should be ARCH=ppc.

Here is the link to ppc yocto images. Hope this helps.
