### ISSUE TITLE
README.rst wrong symlink

### ISSUE THREAD

**Issue by razvand** [linux-kernel-labs/linux#146]
The `README.rst` symbolic link in the root directory points to `Documentation/labs/index.rst`, but it's now `Documentation/teaching/index.rst`.

Should we remove the `README.rst` symbolic link **or** fix it to point to `Documentation/teaching/index.rst`?

**Comment by dbaluta** [comment]
@razvand Yes.

**Comment by razvand** [comment]
@dbaluta , sorry, I worded the question wrong. See now. It's an A **or** B question.

**Comment by dbaluta** [comment]
@razvand created https://github.com/linux-kernel-labs/linux/pull/147

It would be strange to have both README and README.rst but it is useful because github shows a nice landing page with README.rst content.

**Comment by razvand** [comment]
Solved in #147
