### ISSUE TITLE
error on "make boot"

### ISSUE THREAD

**Issue by COOLMSF** [linux-kernel-labs/linux#224]
```
$ make boot
mkdir /tmp/tmp.d5BYbqHJg6
sudo mount -t ext4 -o loop core-image-minimal-qemux86.ext4 /tmp/tmp.d5BYbqHJg6
sudo make -C /home/coolder/Git/linux modules_install INSTALL_MOD_PATH=/tmp/tmp.d5BYbqHJg6
make: Entering directory '/home/coolder/Git/linux'
  INSTALL crypto/crypto_engine.ko
  INSTALL drivers/crypto/virtio/virtio_crypto.ko
  INSTALL drivers/net/netconsole.ko
  DEPMOD  4.19.0+
make: Leaving directory '/home/coolder/Git/linux'
sudo umount /tmp/tmp.d5BYbqHJg6
rmdir /tmp/tmp.d5BYbqHJg6
sleep 1 && touch .modinst
qemu/create_net.sh tap0

dnsmasq: failed to create listening socket for 172.213.0.1: Address already in use
qemu/create_net.sh tap1

dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
/home/coolder/Git/linux/tools/labs/templates/assignments/6-e100/nttcp -v -i &
nttcp-l: nttcp, version 1.47
nttcp-l: running in inetd mode on port 5037 - ignoring options beside -v and -p
bind: Address already in use
nttcp-l: service-socket: bind:: Address already in use, errno=98
```
When I try to connect to it, I got, nothing happens next.
```
Welcome to minicom 2.7.1                                                    
                                                                            
OPTIONS: I18n                                                               
Compiled on May  3 2018, 15:20:11.                                          
Port serial.pts, 02:47:06                                                   
                                                                            
Press CTRL-A Z for help on special keys                                     
```
rather than
```
$ minicom -D serial.pts

Poky (Yocto Project Reference Distro) 2.3 qemux86 /dev/hvc0

qemux86 login: root
root@qemux86:~#
```

**Comment by COOLMSF** [comment]
> ```
> $ make boot
> mkdir /tmp/tmp.d5BYbqHJg6
> sudo mount -t ext4 -o loop core-image-minimal-qemux86.ext4 /tmp/tmp.d5BYbqHJg6
> sudo make -C /home/coolder/Git/linux modules_install INSTALL_MOD_PATH=/tmp/tmp.d5BYbqHJg6
> make: Entering directory '/home/coolder/Git/linux'
>   INSTALL crypto/crypto_engine.ko
>   INSTALL drivers/crypto/virtio/virtio_crypto.ko
>   INSTALL drivers/net/netconsole.ko
>   DEPMOD  4.19.0+
> make: Leaving directory '/home/coolder/Git/linux'
> sudo umount /tmp/tmp.d5BYbqHJg6
> rmdir /tmp/tmp.d5BYbqHJg6
> sleep 1 && touch .modinst
> qemu/create_net.sh tap0
> 
> dnsmasq: failed to create listening socket for 172.213.0.1: Address already in use
> qemu/create_net.sh tap1
> 
> dnsmasq: failed to create listening socket for 127.0.0.1: Address already in use
> /home/coolder/Git/linux/tools/labs/templates/assignments/6-e100/nttcp -v -i &
> nttcp-l: nttcp, version 1.47
> nttcp-l: running in inetd mode on port 5037 - ignoring options beside -v and -p
> bind: Address already in use
> nttcp-l: service-socket: bind:: Address already in use, errno=98
> ```
> 
> When I try to connect to it, I got
> 
> ```
> Welcome to minicom 2.7.1                                                    
>                                                                             
> OPTIONS: I18n                                                               
> Compiled on May  3 2018, 15:20:11.                                          
> Port serial.pts, 02:47:06                                                   
>                                                                             
> Press CTRL-A Z for help on special keys                                     
> ```
> 
> rather than
> 
> ```
> $ minicom -D serial.pts
> 
> Poky (Yocto Project Reference Distro) 2.3 qemux86 /dev/hvc0
> 
> qemux86 login: root
> root@qemux86:~#
> ```

I am runnning on
```
$ uname -a
Linux ubuntu 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dbaluta** [comment]
@COOLMSF can you try again? We fixed similar issues in the past weeks?

**Comment by pppkkkuuu** [comment]
I encountered the same problem,  can you elaborate on how to fix the issue?
Here is my system info:
```
Linux ubuntu 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
