### ISSUE TITLE
Make boot fails

### ISSUE THREAD

**Issue by kukka55** [linux-kernel-labs/linux#23]
student@eg106:~/so2/linux/tools/labs$ QEMU_DISPLAY=sdl make boot
mkdir /tmp/tmp.OGk8onAW85
sudo mount -t ext4 -o loop core-image-minimal-qemux86.ext4 /tmp/tmp.OGk8onAW85
sudo make -C /home/student/so2/linux modules_install INSTALL_MOD_PATH=/tmp/tmp.OGk8onAW85
make: Entering directory '/home/student/so2/linux'
  INSTALL crypto/authenc.ko
  INSTALL crypto/authencesn.ko
  INSTALL crypto/crypto_engine.ko
  INSTALL drivers/crypto/virtio/virtio_crypto.ko
  DEPMOD  4.15.0+
depmod: FATAL: renameat(/tmp/tmp.OGk8onAW85/lib/modules/4.15.0+, modules.dep.tmp, /tmp/tmp.OGk8onAW85/lib/modules/4.15.0+, modules.dep): Structure needs cleaning
Makefile:1252: recipe for target '_modinst_post' failed
make: *** [_modinst_post] Error 1
make: Leaving directory '/home/student/so2/linux'
qemu/Makefile:40: recipe for target '.modinst' failed
make: *** [.modinst] Error 2

**Comment by tavip** [comment]
This looks like filesystem corruption. Can you please try to remove the .ext4 file and try again?

**Comment by tavip** [comment]
Please add steps to reproduce. 

My guess is that a VM instance is already running when running make boot, which causes the FS corruption, but we need steps to reproduce to confirm.
