### ISSUE TITLE
Documentation build fails when using Ubuntu 20.04

### ISSUE THREAD

**Issue by dbaluta** [linux-kernel-labs/linux#235]
@Sergiu121 It looks like Github Actions switched from Ubuntu 18.04 to 20.04 and now Documentation build fails:

For the same PR,
 - Build with 18.04 is OK: https://github.com/linux-kernel-labs/linux/actions/runs/609941412
 - Build with 20.04 is NOT OK: https://github.com/linux-kernel-labs/linux/runs/2005613741

@Sergiu121 @tavip can you have a look if you have some time? As an workaround we could instruct Github Workflow to use Ubuntu 18.04

**Comment by tavip** [comment]
I'll put a PR to use 18.04 for now and will investigate later.
