### ISSUE TITLE
Dockerfile in "https://github.com/linux-kernel-labs/docker" requires "linux/tools/labs/requirements.txt", however there isn't, how can i do?

### ISSUE THREAD

**Issue by giorgiofarina** [linux-kernel-labs/linux#243]

**Comment by dbaluta** [comment]
It was removed with this commit:

commit d8f434ae5175f9ac74d7b5dec10b782d2d870879
Author: Octavian Purdila <tavi@cs.pub.ro>
Date:   Sun Mar 1 17:52:38 2020 +0200

    tools: labs: remove pip install from docs make target
    
    pip depedencies belong to the host setup environment. We will provide
    a Dockerfile to deal with host dependencies.
    
    Signed-off-by: Octavian Purdila <tavi@cs.pub.ro>


@Sergiu121 can you pint to @giorgiofarina how to proceed with docker build?
