### ISSUE TITLE
Block device drivers lab is outdated

### ISSUE THREAD

**Issue by walac** [linux-kernel-labs/linux#260]
Linux 5.0 have some break changes for the block devices API, in special how the request queue is handled. [This article](https://prog.world/linux-kernel-5-0-we-write-simple-block-device-under-blk-mq/) summarizes the new API. We should update the lab with the updated API.

**Comment by dbaluta** [comment]
@walac thanks for pointing this out. I will have a look in the weekend. Please also be advised that it will be fixed in a time frame of 2-3 weeks. That's the moment when our students will need to take this lab.

Also, feel free to send patches if you want.
