### ISSUE TITLE
Unable to build the documentation from the sources

### ISSUE THREAD

**Issue by sumitb** [linux-kernel-labs/linux#3]
I receive the following error on my Macbook.
`make docs`
>make: realpath: Command not found
make: realpath: Command not found
make: realpath: Command not found
make: realpath: Command not found
make: realpath: Command not found
make: realpath: Command not found
make: realpath: Command not found
make: realpath: Command not found
/Library/Developer/CommandLineTools/usr/bin/make -C  DOCBOOKS= SPHINXDIRS=labs htmldocs
make: *** DOCBOOKS=: No such file or directory.  Stop.
make: *** [docs] Error 2

**Comment by dbaluta** [comment]
Hi @sumitb .

Apparently there is no realpath command on Mac so you can try this solution:

https://github.com/google/enjarify/issues/9

**Comment by sumitb** [comment]
`brew install coreutils` fixed it for me 👍

**Comment by sumitb** [comment]
I had to install following packages to:
`brew install graphviz ImageMagick`
`sudo -H pip install sphinx sphinx_rtd_theme`
