### ISSUE TITLE
lx-ps failed with error: 'gdb.Value' object has no attribute 'format_string'

### ISSUE THREAD

**Issue by woodpenker** [linux-kernel-labs/linux#303]
I happen to meet this error when running `lx-ps` inside `gdb`.
```
Traceback (most recent call last):
  File "/home/pilot/codes/linux/scripts/gdb/linux/tasks.py", line 79, in invoke
    task.format_string().split()[0],
AttributeError: 'gdb.Value' object has no attribute 'format_string'
Error occurred in Python command: 'gdb.Value' object has no attribute 'format_string'
```

I solved this error by modifying the code like this:
```
--- a/scripts/gdb/linux/tasks.py
+++ b/scripts/gdb/linux/tasks.py
@@ -76,9 +76,9 @@ class LxPs(gdb.Command):
         gdb.write("{:>10} {:>12} {:>7}\n".format("TASK", "PID", "COMM"))
         for task in task_lists():
             gdb.write("{} {:^5} {}\n".format(
-                task.format_string().split()[0],
-                task["pid"].format_string(),
-                task["comm"].string()))
+                str(task).split()[0],
+                str(task["pid"]),
+                str(task["comm"].string())))
```

Hope to help others.

**Comment by dbaluta** [comment]
Care to send a patch for this? Maybe it is because of your python version.

**Comment by woodpenker** [comment]
> Care to send a patch for this? Maybe it is because of your python version.

My Python version is 3.6.8.  Is this the root cause?

**Comment by woodpenker** [comment]
> > My Python version is 3.6.8. Is this the root cause?
> 
> This could be. I think at the moment @tavip wrote this we were using python2.7. Let see if tavi has more insights on this. Can you try it with python2.7?

Thanks, I find that Ubuntu's gdb default uses py3, but I have no idea how to change it to py2. Some similar cases I can find on google, so this failure sounds reasonable.

**Comment by Manouchehri** [comment]
Ran into this issue as well.

Is Python 2 what we're still supposed to be using? (I don't have a problem with it, just wondering what's "supported" or not.)
