### ISSUE TITLE
cannot Connecting to the Virtual Machine through minicom

### ISSUE THREAD

**Issue by linaki-o** [linux-kernel-labs/linux#369]
after i done all the step，and i run `make boot` in a window and run `minicom -D serial.pts` in another window.
but i can see nothing but this below:
<img width="472" alt="image" src="https://github.com/linux-kernel-labs/linux/assets/78514733/9dcee3e8-ca6a-4652-b5b7-8963f45397d5">

it doesn't have linux promt in the lab 
`
.../linux/tools/labs$ minicom -D serial.pts
[...]
Poky (Yocto Project Reference Distro) 2.3 qemux86 /dev/hvc0

qemux86 login: root
root@qemux86:~#
`

does anybody know what's wrong about it? thx

**Comment by dbaluta** [comment]
Depending on your setup sometimes can be a little bit slow. So waiting some more time should help.

Another part is that you must be sure that you have used the `.config` file we provided. 

So, can you please remove your .config file in the source tree directory and then run make boot again.

**Comment by linaki-o** [comment]
Thank u sir.
after waiting for a few minutes, thing succeeded.
i think i need to be more patient :)
